server:
  port: 8080

spring:
  application:
    name: stock-analysis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 1000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{requestId}] %-5level %logger{36} - %msg%n"
  level:
    com.stock.analysis: DEBUG
